//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWCF
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Cheque", Namespace = "http://schemas.datacontract.org/2004/07/TestWcfService")]
    [System.SerializableAttribute()]
    public partial class Cheque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ArticlesField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiscountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SummField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Articles
        {
            get
            {
                return this.ArticlesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ArticlesField, value) != true))
                {
                    this.ArticlesField = value;
                    this.RaisePropertyChanged("Articles");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                if ((this.DiscountField.Equals(value) != true))
                {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NumberField, value) != true))
                {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Summ
        {
            get
            {
                return this.SummField;
            }
            set
            {
                if ((this.SummField.Equals(value) != true))
                {
                    this.SummField = value;
                    this.RaisePropertyChanged("Summ");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ExportCheque", Namespace = "http://schemas.datacontract.org/2004/07/TestWcfService")]
    [System.SerializableAttribute()]
    public partial class ExportCheque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticlesField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SummField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Articles
        {
            get
            {
                return this.ArticlesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ArticlesField, value) != true))
                {
                    this.ArticlesField = value;
                    this.RaisePropertyChanged("Articles");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                if ((this.DiscountField.Equals(value) != true))
                {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdField, value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NumberField, value) != true))
                {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Summ
        {
            get
            {
                return this.SummField;
            }
            set
            {
                if ((this.SummField.Equals(value) != true))
                {
                    this.SummField = value;
                    this.RaisePropertyChanged("Summ");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "testWCF.ITestWCFService")]
    public interface ITestWCFService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWCFService/InsertCheques", ReplyAction = "http://tempuri.org/ITestWCFService/InsertChequesResponse")]
        void InsertCheques(testWCF.Cheque cheques);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWCFService/InsertCheques", ReplyAction = "http://tempuri.org/ITestWCFService/InsertChequesResponse")]
        System.Threading.Tasks.Task InsertChequesAsync(testWCF.Cheque cheques);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWCFService/GetN", ReplyAction = "http://tempuri.org/ITestWCFService/GetNResponse")]
        testWCF.ExportCheque[] GetN(int n);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWCFService/GetN", ReplyAction = "http://tempuri.org/ITestWCFService/GetNResponse")]
        System.Threading.Tasks.Task<testWCF.ExportCheque[]> GetNAsync(int n);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestWCFServiceChannel : testWCF.ITestWCFService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestWCFServiceClient : System.ServiceModel.ClientBase<testWCF.ITestWCFService>, testWCF.ITestWCFService
    {

        public TestWCFServiceClient()
        {
        }

        public TestWCFServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public TestWCFServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public TestWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public TestWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public void InsertCheques(testWCF.Cheque cheques)
        {
            base.Channel.InsertCheques(cheques);
        }

        public System.Threading.Tasks.Task InsertChequesAsync(testWCF.Cheque cheques)
        {
            return base.Channel.InsertChequesAsync(cheques);
        }

        public testWCF.ExportCheque[] GetN(int n)
        {
            return base.Channel.GetN(n);
        }

        public System.Threading.Tasks.Task<testWCF.ExportCheque[]> GetNAsync(int n)
        {
            return base.Channel.GetNAsync(n);
        }
    }
}
